import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
// import { store } from "@/store/store";
// import { Provider } from "react-redux";

const work_Sans = Work_Sans({
  subsets: ["latin"],
  weight: ["300", "100", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${work_Sans.className}  antialiased`}>
        {children}
        </body>
    </html>
  );
}
